#!/usr/bin/env node
import { writeFileSync, existsSync, readFileSync } from "node:fs";
import { execSync } from "node:child_process";

export function runInit(argv: string[]): number {
  const yes = argv.includes("--yes");
  const configPath = ".driftguard.yml";
  if (existsSync(configPath) && !yes) {
    console.error(`${configPath} already exists — use --yes to overwrite`);
    return 2;
  }

  let specPath = "openapi.yaml";
  for (const candidate of ["openapi.yaml", "openapi.json", "api/openapi.yaml", "docs/openapi.yaml"]) {
    if (existsSync(candidate)) {
      specPath = candidate;
      break;
    }
  }

  let serviceName = "my-service";
  try {
    const pkg = JSON.parse(readFileSync("package.json", "utf8")) as { name?: string };
    if (pkg.name) serviceName = pkg.name.replace(/^@.*\//, "");
  } catch {
    /* optional */
  }

  let gitRemote = "";
  try {
    gitRemote = execSync("git remote get-url origin", { encoding: "utf8" }).trim();
  } catch {
    /* optional */
  }

  const yaml = `# Generated by driftguard init
specPath: ${specPath}
failOnBreaking: true
remote:
  enabled: false
serviceName: ${serviceName}
${gitRemote ? `# gitRemote: ${gitRemote}\n` : ""}`;
  writeFileSync(configPath, yaml);
  console.log(`Wrote ${configPath}`);
  console.log(`Next: driftguard openapi-diff ${specPath} ${specPath} --fail-on-breaking`);
  return 0;
}
